### PR TITLE
Enable article coding

### PR DESCRIPTION
**Pull request by davidskalinder**
All right, PR time!  This is the big one: it enables coding information (such as article description and whether an article contains protests) at the article level rather than at event level.  This code should create a new table (so requires running init_db) to store the article info, and provides the usual stuff (data IO from the table, JS listeners, and JS handlers).

Note that in violation of my goal of entirely separating enabling stuff from implementing it, this code does create a template for the article block and moves some of the items from the event block to the article block.  So if you want to merge this code invisibly, you might want to refuse the changes to the templates or merge them into a separate branch of something.  Let me know if more info would help with that.

### CODE REVIEW

**Comment by alexhanna** [comment]
Sorry, I just realized this clobbers out article level coding the way we were doing it too. Gotta revert.

**Comment by davidskalinder** [comment]
This reversion surprises me less, since this is a major change.  However looking at my comment above to refresh my memory, it looks like you can avoid clobbering the old setup by simply reinstating the old templates (and accepting the under-the-hood changes everywhere else)?  If that's wrong, or right but a PITA that I can help reduce, let me know...

**Comment by alexhanna** [comment]
Not sure what you mean "reinstating the old templates"? Which ones? This change got rid of the article-level coding block, and our coding hasn't really distinguished between article-level and event-level yet.

**Comment by davidskalinder** [comment]
Yeah sorry I did a bad job keeping under-the-hood stuff and user-visible stuff separate on this one.  But I think the only things in this PR that actually change the HTML blocks are the changes to `templates/event-creator-block.html` and `templates/event-creator.html` (though I'm also a little suspicious of the changes in the controller's `markECDone()` function, although I don't remember for sure.  Everything else should be under the hood: you could in theory accept all the changes except to those files and everything would look the same to everyone unless and until you decide to add `<div id="article-annotation-blocks" class="varlist"></div>` to `templates/event-creator.html`.  Without that, anything collected about the article is just one more piece of info about each event, like it always has been.

Having said that:

1. I think this will still require a change to the DB, though this time I think it can happen with a call to `init_db()` since it seems we can create new tables this way (it'll create an article-level table that will remain empty unless you decide to activate a new template to put stuff into it).  But if you don't want to touch your DB at all, then yeah I think that dooms this PR.
1. This is definitely a major change, so if I were you I wouldn't want to accept it partially or fully without testing it to make sure it works with y'all's setup.

So, very much understand if all this is too much of a pain to be worthwhile for right now...

**Comment by alexhanna** [comment]
A few things fail on this PR besides the database change. The immediate one is that `modifyArticleAnnotations()` is in the doc ready function in ec.js so it throws an error off the bat. The database change isn't a huge deal if you don't want to implement any of the other blocks, except that it clobbers the article annotation. We should discuss this in more detail in our next meeting.

**Pull request merged**
