### PR TITLE
Enable article dates

### PR DESCRIPTION
**Pull request by davidskalinder**
This one adds a date field to the article_metadata column when the table is created.  The column would need to be populated externally (same as the title column), and it allows nulls, so the change should be invisible if you ignore it (and indeed, so far I don't think I've even written any features that use it, so it's only visible in the back end for now).

As discussed in https://github.com/davidskalinder/mpeds-coder/issues/39, this only seems to work on table creation, so for existing tables you'd need to run `ALTER TABLE article_metadata ADD COLUMN pub_date DATE;` or come up with a cleverer way of changing the table.

### CODE REVIEW

**Comment by alexhanna** [comment]
Sorry @davidskalinder I have to pull this out of master. This broke my instantiation because I didn't do a new database version with article_metadata.pub_date.

**Comment by davidskalinder** [comment]
Yeah, no worries, feel free to reject away, with any of these!  However I think this one has an easy solution if you run the poor-man's database migration `ALTER TABLE article_metadata ADD COLUMN pub_date DATE;`?

**Comment by alexhanna** [comment]
One could do that, but the prospect of doing that to a live database terrifies me.

**Comment by davidskalinder** [comment]
Hmm yes, I sympathize with this terror.  As we discussed in https://github.com/davidskalinder/mpeds-coder/issues/39 though, I'm not sure we have a sensible alternative if we ever want to make any changes to the DB though?

I suppose another option that's kind of a middle ground would be for you to set up a testing deployment and migrate that first (we have a dev deployment that I break all the time, a testing deployment for the team to check, and then the production one after that).  But of course that requires a fair amount of effort to set up and still doesn't rule out any problems with the live data...

Otherwise I'm not sure what we can do other than to have the forks diverge on any changes that touch the database?...

**Pull request merged**
