### PR TITLE
Enable select controls

### PR DESCRIPTION
**Pull request by davidskalinder**
This one shoehorns in the ability to use select controls in the basic info tab.  I did this by using the same handlers and stuff as are used for radios, but having gotten more familiar with the system since then I notice that select controls are already used in the admin interface, so maybe I should have ported that functionality to the event coding areas rather than piggybacking on the radios?  So if so, feel free to reject this one and let me know that there's an easier way (which I'll then probably use if I use selects on some other tab in the future).

### CODE REVIEW

**Comment by alexhanna** [comment]
I don't quite follow the logic of this one. What does it do?

**Comment by davidskalinder** [comment]
This one enables drop-downs in the basic info tab of the event coder screen.  I don't think it actually adds any, but it should let them be added to templates the way radios and umm like text inputs were previously I think?  It's been a while since I did this though, so let me know if you want more detail and I can actually like look at the code...

**Comment by davidskalinder** [comment]
Ah, yes, I remember -- the trick here is that the logic to handle the select inputs is exactly the same as for the radio inputs, so I just made a select input listener and pointed it at the radio handler.

**Comment by alexhanna** [comment]
Ah okay. That's innocuous enough.

**Pull request merged**
