### PR TITLE
Changed sticky blocks to static to make them scroll

### PR DESCRIPTION
**Pull request by davidskalinder**
This fixes this bug: https://github.com/davidskalinder/mpeds-coder/issues/25 -- wherein sometimes things toward the bottom of the coding area will get cut off on small screens.  However, there is a trade-off (mentioned at the bottom of the issue and at https://github.com/davidskalinder/mpeds-coder/issues/51), namely that coders will have to scroll back to the top of long articles in order to code them.

This should be the last PR for this batch: I think the rest of our changes are project-specific.

### CODE REVIEW

**Comment by davidskalinder** [comment]
Whoops, does deleting branches close the PRs from those branches?  There oughta be a warning message...  Anyway guess I should restore all these branches from like February huh...

**Comment by alexhanna** [comment]
I don't think I like this functionality. Can we look at this together in our next 1:1?

**Comment by davidskalinder** [comment]
Yeah for shizzle.  This fix is definitely mediocre, and the previous version is better unless the coding panel is long enough to hang below the bottom of the page.  I think https://github.com/davidskalinder/mpeds-coder/issues/51 is the ultimate solution, but I haven't gotten to that yet.  Let's discuss synchronously next time we catch up (which, feel free to email to schedule?).

**Comment by alexhanna** [comment]
Choosing to part ways on this design.

**Pull request closed without merging**
