### PR TITLE
merging in HTML fix. removes arbitrary HTML from body text. also upda…

### PR DESCRIPTION
**Pull request by alexhanna**
merging in HTML fix. removes arbitrary HTML from body text. also updates Publication report

### CODE REVIEW

**Comment by davidskalinder** [comment]
So I just pulled this fix into my `upstream_development` branch (which is what I build new features on top of by default so that any Pull Requests back upstream will be clean), and I noticed that the fix replaces the "Publication report" entry on the admin home screen with "Publication report UWIRE | Canadian | HBCUs", with the last three linked to something that your project is presumably using!

Since this is obviously a project-specific change, I wanted to check if I should do anything about it on my end.  I don't *think* we on the BPP side care about this change?  @olderwoman, do we ever use the "Publication report" feature, or do we have any plans to?  (To clarify, if I proceed as usual, this change will eventually show up in our deployments.)

@alexhanna, I think this is the first time that anything you've done for your projects has created even a hint of conflict on our end, so maybe this won't cause any problems; but if there's some obviously better strategy I should use instead of pulling your master branch into the default starting point for my features, please feel free to point me in that better direction!

**Comment by alexhanna** [comment]
Ack, yeah. I made a small fix to another piece of the project and this change was incorporated into it. I don't think this should live under version control, however. I think I'm going to revert this change and make the smaller, HTML fix.

**Comment by davidskalinder** [comment]
Okay sounds good.  I think for the time being I'll revert my branch back a few commits and build on that?...  And then I can update it again once you've got things settled.

**Comment by alexhanna** [comment]
I made a new commit in the reversion so you should be able to be even with master and build from there. Sorry about that.

**Comment by davidskalinder** [comment]
Fab, thanks.  No worries!

**Pull request merged**
